In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import f_regression, mutual_info_regression

In [10]:
# Carga de datos.
np.random.seed(0)
X = np.random.rand(1000, 3)
print(X)


[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 ...
 [0.47521403 0.28729288 0.87968154]
 [0.28492705 0.94168707 0.54613275]
 [0.32361371 0.81354502 0.69740038]]


In [ ]:
y = X[:, 0] + np.sin(6 * np.pi * X[:, 1]) + 0.1 * np.random.randn(1000)
print(y)

In [ ]:
# Evaluación de atributos: F-Test.
f_test, _ = f_regression(X, y)
f_test /= np.max(f_test)

In [ ]:
# Evaluación de atributos: información mutua.
mi = mutual_info_regression(X, y)
mi /= np.max(mi)

In [ ]:
# Graficar distribución de los datos y evaluación de atributos.
plt.figure(figsize=(15, 5))
for i in range(3):
    plt.subplot(1, 3, i + 1)
    plt.scatter(X[:, i], y, edgecolor='black', s=20)
    plt.xlabel("$x_{}$".format(i + 1), fontsize=14)
    if i == 0:
        plt.ylabel("$y$", fontsize=14)
    plt.title("F-test={:.2f}, MI={:.2f}".format(f_test[i],
              mi[i]), fontsize=16)
plt.show()